package response

import "net/http"

// TitleByStatus provides default titles for HTTP status codes
var TitleByStatus = map[int]string{
	http.StatusBadRequest:                    "Bad Request",
	http.StatusUnauthorized:                  "Unauthorized",
	http.StatusForbidden:                     "Forbidden",
	http.StatusNotFound:                      "Resource Not Found",
	http.StatusMethodNotAllowed:              "Method Not Allowed",
	http.StatusNotAcceptable:                 "Not Acceptable",
	http.StatusRequestTimeout:                "Request Timeout",
	http.StatusConflict:                      "Conflict",
	http.StatusGone:                          "Gone",
	http.StatusLengthRequired:                "Length Required",
	http.StatusPreconditionFailed:            "Precondition Failed",
	http.StatusRequestEntityTooLarge:         "Request Entity Too Large",
	http.StatusRequestURITooLong:             "Request URI Too Long",
	http.StatusUnsupportedMediaType:          "Unsupported Media Type",
	http.StatusRequestedRangeNotSatisfiable:  "Requested Range Not Satisfiable",
	http.StatusExpectationFailed:             "Expectation Failed",
	http.StatusTeapot:                        "I'm a teapot",
	http.StatusMisdirectedRequest:            "Misdirected Request",
	http.StatusUnprocessableEntity:           "Validation Failed",
	http.StatusLocked:                        "Locked",
	http.StatusFailedDependency:              "Failed Dependency",
	http.StatusTooEarly:                      "Too Early",
	http.StatusUpgradeRequired:               "Upgrade Required",
	http.StatusPreconditionRequired:          "Precondition Required",
	http.StatusTooManyRequests:               "Too Many Requests",
	http.StatusRequestHeaderFieldsTooLarge:   "Request Header Fields Too Large",
	http.StatusUnavailableForLegalReasons:    "Unavailable For Legal Reasons",
	http.StatusInternalServerError:           "Internal Server Error",
	http.StatusNotImplemented:                "Not Implemented",
	http.StatusBadGateway:                    "Bad Gateway",
	http.StatusServiceUnavailable:            "Service Unavailable",
	http.StatusGatewayTimeout:                "Gateway Timeout",
	http.StatusHTTPVersionNotSupported:       "HTTP Version Not Supported",
	http.StatusVariantAlsoNegotiates:         "Variant Also Negotiates",
	http.StatusInsufficientStorage:           "Insufficient Storage",
	http.StatusLoopDetected:                  "Loop Detected",
	http.StatusNotExtended:                   "Not Extended",
	http.StatusNetworkAuthenticationRequired: "Network Authentication Required",
}

// DetailByStatus provides default detail messages for HTTP status codes
var DetailByStatus = map[int]string{
	http.StatusBadRequest:                    "The request is invalid or malformed. Please check your request and try again.",
	http.StatusUnauthorized:                  "Authentication is required to access this resource. Please provide valid credentials.",
	http.StatusForbidden:                     "You do not have permission to access this resource.",
	http.StatusNotFound:                      "The requested resource could not be found on the server.",
	http.StatusMethodNotAllowed:              "The HTTP method used is not allowed for this resource.",
	http.StatusNotAcceptable:                 "The requested resource cannot be provided in a format acceptable to the client.",
	http.StatusRequestTimeout:                "The server timed out waiting for the request.",
	http.StatusConflict:                      "The request conflicts with the current state of the resource.",
	http.StatusGone:                          "The requested resource is no longer available on the server.",
	http.StatusLengthRequired:                "The request must include a Content-Length header.",
	http.StatusPreconditionFailed:            "One or more conditions specified in the request headers failed.",
	http.StatusRequestEntityTooLarge:         "The request entity is larger than the server is willing to process.",
	http.StatusRequestURITooLong:             "The request URI is longer than the server is willing to interpret.",
	http.StatusUnsupportedMediaType:          "The request entity has a media type that the server does not support.",
	http.StatusRequestedRangeNotSatisfiable:  "The requested range cannot be satisfied by the server.",
	http.StatusExpectationFailed:             "The server cannot meet the requirements of the Expect request header.",
	http.StatusTeapot:                        "I'm a teapot. This status code is defined in RFC 2324.",
	http.StatusMisdirectedRequest:            "The request was directed at a server that is not able to produce a response.",
	http.StatusUnprocessableEntity:           "The provided data failed validation requirements. Please check your input and try again.",
	http.StatusLocked:                        "The requested resource is currently locked.",
	http.StatusFailedDependency:              "The request failed due to failure of a previous request.",
	http.StatusTooEarly:                      "The server is unwilling to risk processing a request that might be replayed.",
	http.StatusUpgradeRequired:               "The client should switch to a different protocol.",
	http.StatusPreconditionRequired:          "The origin server requires the request to be conditional.",
	http.StatusTooManyRequests:               "The user has sent too many requests in a given amount of time.",
	http.StatusRequestHeaderFieldsTooLarge:   "The server is unwilling to process the request because its header fields are too large.",
	http.StatusUnavailableForLegalReasons:    "The requested resource is unavailable for legal reasons.",
	http.StatusInternalServerError:           "An unexpected error occurred on the server. Please try again later.",
	http.StatusNotImplemented:                "The server does not support the functionality required to fulfill the request.",
	http.StatusBadGateway:                    "The server received an invalid response from an upstream server.",
	http.StatusServiceUnavailable:            "The server is currently unavailable. Please try again later.",
	http.StatusGatewayTimeout:                "The server did not receive a timely response from an upstream server.",
	http.StatusHTTPVersionNotSupported:       "The server does not support the HTTP protocol version used in the request.",
	http.StatusVariantAlsoNegotiates:         "The server has an internal configuration error.",
	http.StatusInsufficientStorage:           "The server is unable to store the representation needed to complete the request.",
	http.StatusLoopDetected:                  "The server detected an infinite loop while processing the request.",
	http.StatusNotExtended:                   "Further extensions to the request are required for the server to fulfill it.",
	http.StatusNetworkAuthenticationRequired: "The client needs to authenticate to gain network access.",
}
