openapi: 3.0.3
info:
  title: Go Hexagonal Fullstack Monorepo API
  description: API specification for the Go hexagonal architecture monorepo
  version: 1.0.0
  contact:
    name: Tech Forge LAT
    url: https://github.com/techforge-lat/go-hexagonal-fullstack-monorepo
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:8080
    description: Development server

paths:
  /users:
    post:
      summary: Create a new user
      description: Creates a new user with the provided information
      operationId: createUser
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserCreateRequest"
            examples:
              basic_user:
                summary: Basic user creation
                value:
                  id: "123e4567-e89b-12d3-a456-426614174000"
                  firstName: "John"
                  lastName: "Doe"
                  origin: "web_signup"
                  picture: "https://example.com/avatar.jpg"
                  createdAt: "2023-01-01T00:00:00Z"
      responses:
        "201":
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
              examples:
                success:
                  summary: Successful creation
                  value:
                    type: "about:blank"
                    title: "Recurso Creado"
                    detail: "El recurso fue creado exitosamente"
                    status: 201
                    data:
                      id: "123e4567-e89b-12d3-a456-426614174000"
                      firstName: "John"
                      lastName: "Doe"
                      origin: "web_signup"
                      picture: "https://example.com/avatar.jpg"
        "400":
          $ref: "#/components/responses/BadRequest"
        "422":
          $ref: "#/components/responses/ValidationError"
        "500":
          $ref: "#/components/responses/InternalError"

    get:
      summary: List users
      description: Retrieves a list of users with optional filtering, sorting, and pagination
      operationId: listUsers
      tags:
        - Users
      parameters:
        - $ref: "#/components/parameters/SelectParam"
        - $ref: "#/components/parameters/PaginationParam"
        - name: firstName
          in: query
          description: "Filter by firstName OR Sort by firstName. Filter format: operator:value[:chaining]. Sort format: sort:direction. Operators: eq, ne, gt, gte, lt, lte, like, in, nin, contains, ncontains, is, isn. Chaining: and (default), or. Direction: asc, desc"
          schema:
            type: string
            example: "eq:John"
        - name: lastName
          in: query
          description: "Filter by lastName OR Sort by lastName. Filter format: operator:value[:chaining]. Sort format: sort:direction. Operators: eq, ne, gt, gte, lt, lte, like, in, nin, contains, ncontains, is, isn. Chaining: and (default), or. Direction: asc, desc"
          schema:
            type: string
            example: "eq:Doe"
        - name: origin
          in: query
          description: "Filter by origin OR Sort by origin. Filter format: operator:value[:chaining]. Sort format: sort:direction. Operators: eq, ne, gt, gte, lt, lte, like, in, nin, contains, ncontains, is, isn. Chaining: and (default), or. Direction: asc, desc"
          schema:
            type: string
            example: "in:web_signup,mobile_app"
        - name: picture
          in: query
          description: "Filter by picture OR Sort by picture. Filter format: operator:value[:chaining]. Sort format: sort:direction. Operators: eq, ne, gt, gte, lt, lte, like, in, nin, contains, ncontains, is, isn. Chaining: and (default), or. Direction: asc, desc"
          schema:
            type: string
            example: "contains:avatar"
        - name: createdAt
          in: query
          description: "Filter by createdAt OR Sort by createdAt. Filter format: operator:value[:chaining]. Sort format: sort:direction. Operators: eq, ne, gt, gte, lt, lte, like, in, nin, contains, ncontains, is, isn. Chaining: and (default), or. Direction: asc, desc"
          schema:
            type: string
            example: "gte:2023-01-01T00:00:00Z"
      responses:
        "200":
          description: List of users retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
              examples:
                success:
                  summary: Successful list
                  value:
                    type: "about:blank"
                    status: 200
                    data:
                      - id: "123e4567-e89b-12d3-a456-426614174000"
                        firstName: "John"
                        lastName: "Doe"
                        origin: "web_signup"
                        createdAt: "2023-01-01T00:00:00Z"
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalError"

  /users/{id}:
    get:
      summary: Get user by ID
      description: Retrieves a specific user by their ID
      operationId: getUser
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          description: User ID
          schema:
            type: string
            format: uuid
            example: "123e4567-e89b-12d3-a456-426614174000"
        - $ref: "#/components/parameters/SelectParam"
      responses:
        "200":
          description: User retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
              examples:
                success:
                  summary: Successful retrieval
                  value:
                    type: "about:blank"
                    status: 200
                    data:
                      id: "123e4567-e89b-12d3-a456-426614174000"
                      firstName: "John"
                      lastName: "Doe"
                      origin: "web_signup"
                      picture: "https://example.com/avatar.jpg"
                      createdAt: "2023-01-01T00:00:00Z"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalError"

    patch:
      summary: Update user
      description: Updates an existing user with the provided information
      operationId: updateUser
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          description: User ID
          schema:
            type: string
            format: uuid
            example: "123e4567-e89b-12d3-a456-426614174000"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserUpdateRequest"
            examples:
              partial_update:
                summary: Partial user update
                value:
                  firstName: "Jane"
                  lastName: null
                  origin: null
                  picture: "https://example.com/new-avatar.jpg"
                  updatedAt: "2023-01-02T00:00:00Z"
      responses:
        "200":
          description: User updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
              examples:
                success:
                  summary: Successful update
                  value:
                    type: "about:blank"
                    status: 200
                    data:
                      firstName: "Jane"
                      lastName: null
                      origin: null
                      picture: "https://example.com/new-avatar.jpg"
                      updatedAt: "2023-01-02T00:00:00Z"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
        "422":
          $ref: "#/components/responses/ValidationError"
        "500":
          $ref: "#/components/responses/InternalError"

    delete:
      summary: Delete user
      description: Soft deletes a user by their ID
      operationId: deleteUser
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          description: User ID
          schema:
            type: string
            format: uuid
            example: "123e4567-e89b-12d3-a456-426614174000"
      responses:
        "204":
          description: User deleted successfully
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalError"

components:
  schemas:
    User:
      type: object
      description: User entity with all fields
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the user
          example: "123e4567-e89b-12d3-a456-426614174000"
        firstName:
          type: string
          description: User's first name
          minLength: 3
          maxLength: 50
          example: "John"
        lastName:
          type: string
          nullable: true
          description: User's last name (optional)
          maxLength: 50
          example: "Doe"
        origin:
          type: string
          description: Origin of user registration
          minLength: 3
          maxLength: 30
          example: "web_signup"
        picture:
          type: string
          nullable: true
          description: User's profile picture URL
          example: "https://example.com/avatar.jpg"
        createdAt:
          type: string
          format: date-time
          description: Timestamp when user was created
          example: "2023-01-01T00:00:00Z"
        updatedAt:
          type: string
          format: date-time
          nullable: true
          description: Timestamp when user was last updated
          example: "2023-01-02T00:00:00Z"
        deletedAt:
          type: string
          format: date-time
          nullable: true
          description: Timestamp when user was deleted (soft delete)
          example: "2023-01-03T00:00:00Z"
      required:
        - id
        - firstName
        - origin
        - createdAt

    UserCreateRequest:
      type: object
      description: Request payload for creating a new user
      properties:
        id:
          type: string
          format: uuid
          description: User ID
          example: "123e4567-e89b-12d3-a456-426614174000"
        firstName:
          type: string
          description: User's first name
          minLength: 3
          maxLength: 50
          example: "John"
        lastName:
          type: string
          nullable: true
          description: User's last name (optional)
          maxLength: 50
          example: "Doe"
        origin:
          type: string
          description: Origin of user registration
          minLength: 3
          maxLength: 30
          example: "web_signup"
        picture:
          type: string
          nullable: true
          description: User's profile picture URL
          example: "https://example.com/avatar.jpg"
        createdAt:
          type: string
          format: date-time
          nullable: true
          description: Creation timestamp
          example: "2023-01-01T00:00:00Z"
      required:
        - firstName
        - origin

    UserUpdateRequest:
      type: object
      description: Request payload for updating a user
      properties:
        firstName:
          type: string
          nullable: true
          description: User's first name
          minLength: 3
          maxLength: 50
          example: "Jane"
        lastName:
          type: string
          nullable: true
          description: User's last name
          maxLength: 50
          example: "Smith"
        origin:
          type: string
          nullable: true
          description: Origin of user registration
          minLength: 3
          maxLength: 30
          example: "mobile_app"
        picture:
          type: string
          nullable: true
          description: User's profile picture URL
          example: "https://example.com/new-avatar.jpg"
        updatedAt:
          type: string
          format: date-time
          nullable: true
          description: Update timestamp
          example: "2023-01-02T00:00:00Z"

    ApiResponse:
      type: object
      description: Standard API response following RFC 9457 Problem Details
      properties:
        type:
          type: string
          description: Problem type URI
          example: "about:blank"
        title:
          type: string
          description: Problem title
          example: "Recurso Creado"
        detail:
          type: string
          description: Problem detail
          example: "El recurso fue creado exitosamente"
        status:
          type: integer
          description: HTTP status code
          example: 201
        instance:
          type: string
          description: Problem instance URI
          example: "/users/123"
        data:
          description: Response data (varies by endpoint)
          oneOf:
            - $ref: "#/components/schemas/User"
            - type: array
              items:
                $ref: "#/components/schemas/User"
            - $ref: "#/components/schemas/UserCreateRequest"
            - $ref: "#/components/schemas/UserUpdateRequest"

    ErrorResponse:
      type: object
      description: Error response following RFC 9457 Problem Details
      properties:
        type:
          type: string
          description: Problem type URI
          example: "about:blank"
        title:
          type: string
          description: Error title
          example: "Solicitud Incorrecta"
        detail:
          type: string
          description: Error detail
          example: "La solicitud es inválida o está mal formada"
        status:
          type: integer
          description: HTTP status code
          example: 400
        instance:
          type: string
          description: Problem instance URI
          example: "/users"
        debug_error:
          type: string
          description: Debug error information (development only)
          example: "validation failed: firstName is required"
        error_code:
          type: string
          description: Application-specific error code
          example: "VALIDATION_FAILED"

  parameters:
    SelectParam:
      name: select
      in: query
      description: |
        Comma-separated list of fields to include in the response.
        Use "*" to select all fields.
      schema:
        type: string
        example: "id,firstName,lastName"

    PaginationParam:
      name: x
      in: query
      description: |
        Pagination parameters. Format: page:number or limit:size
        Controls page number and page size for results.
        Multiple x parameters can be provided for different pagination settings.
        
        **Examples**:
        - `x=page:1` - Get page 1
        - `x=limit:10` - 10 items per page
        - Multiple: `x=page:2&x=limit:20` - Page 2 with 20 items
      schema:
        type: array
        items:
          type: string
          enum: 
            - "page:1"
            - "page:2"
            - "limit:10"
            - "limit:20"
            - "limit:50"
        example: ["page:1", "limit:10"]

  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          examples:
            bad_request:
              summary: Invalid request
              value:
                type: "about:blank"
                title: "Solicitud Incorrecta"
                detail: "La solicitud es inválida o está mal formada"
                status: 400

    NotFound:
      description: Resource Not Found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          examples:
            not_found:
              summary: Resource not found
              value:
                type: "about:blank"
                title: "Recurso No Encontrado"
                detail: "El recurso solicitado no pudo ser encontrado"
                status: 404

    ValidationError:
      description: Validation Failed
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          examples:
            validation_error:
              summary: Validation failed
              value:
                type: "about:blank"
                title: "Validación Fallida"
                detail: "Los datos proporcionados no cumplen con los requisitos de validación"
                status: 422
                debug_error: "firstName: This field is required"

    InternalError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          examples:
            internal_error:
              summary: Server error
              value:
                type: "about:blank"
                title: "Error Interno del Servidor"
                detail: "Ocurrió un error inesperado en el servidor"
                status: 500

tags:
  - name: Users
    description: User management operations