basePath: /api/v1
definitions:
  response.Response:
    properties:
      data:
        description: Success response field
      detail:
        type: string
      instance:
        type: string
      status:
        type: integer
      title:
        type: string
      type:
        description: RFC 9457 standard fields
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: A Go API service built with hexagonal architecture
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Go Hexagonal API
  version: "1.0"
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Check if the service is healthy and database is reachable
      produces:
      - application/json
      responses:
        "200":
          description: Service is healthy
          schema:
            $ref: '#/definitions/response.Response'
        "503":
          description: Service is unavailable
          schema:
            $ref: '#/definitions/response.Response'
      summary: Health Check
      tags:
      - health
schemes:
- http
- https
swagger: "2.0"
